import type { Metadata } from "next";
import { Inter, Nova_Script } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Square",
  description: "Generated by Chioma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
